# Generated by Django 5.0.1 on 2024-02-14 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
